# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "GORE 19"
email: "gore-org@esnog.net"
description: "ESNOG (España Network Operators Group / Grupo de Operadores de Red Españoles) celebrará su decimonovena reunión el Jueves 6 de Abril y Viernes 7 de Abril de 2017 en el CSUC/CATNIX"
baseurl: "/zeppelin"
url: "https://japidei.github.io/zeppelin"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-93709719-1"
googleAnalyticsSiteUrl: "japidei.github.io"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "ESNOG"
organizerAlternateName: "Grupo de Operadores de Red Españoles"
organizerDescription: "ESNOG es un foro abierto para el intercambio de información técnica, experiencias operacionales y conocimientos de ingeniería relacionados con los servicios de infraestructura de Internet con el objetivo de mejorar el intercambio de experiencias e información entre ingenieros además de aumentar la colaboración y la coordinacion entre redes en España."
organizerEmail: "gore@esnog.net "
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://www.esnog.net/"

# Head
metaKeywords: "event, gdg, devfest, google, programming, android, chrome, developers, lviv"
twitterAccount: "@ESNOG1"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://bit.ly/dfua-c4p"
c4sponsorsUrl: "mailto:gore-org@esnog.net"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/schedule/", text: "Agenda"}
 - {permalink: "/speakers/", text: "Ponentes"}
# - {permalink: "/team/", text: "Equipo"}
 - {permalink: "/logistics/", text: "Logística"}
bottomNavigationLinks:
 - {link: "mailto:gore-org@esnog.net", text: "Conviertase en patrocinador"}
rightNavigationButtons:
 - {link: "mailto:gore-org@esnog.net", text: "Conviertase en patrocinador"}

# Hero Block
#heroImage: "hero.jpg"
heroTitle: Gore <typeout> 19"
eventDate: "Jueves 6 y Viernes 7 de Abril, 2017"
typeoutTextValues: '"", "Barcelona", "CSUC", "CATNIX"'
typeoutFallback: "Barcelona"
heroButtons:
 - {link: "http://www.esnog.net/gore19/gore19-participar-habilitado.html", text: "Incripción"}
 - {link: "http://www.esnog.net/gore19/lista.html", text: "Listado de asistentes"}

# About Block
aboutTitle: "Acerca de GORE 19"
aboutBlock:
 - {title: "Reunión", image: "conference.jpg", text: "ESNOG (España Network Operators Group / Grupo de Operadores de Red Españoles) celebrará su decimonovena reunión el Jueves 6 de Abril y Viernes 7 de Abril de 2017 en el CSUC/CATNIX" }
 - {title: "Presentaciones", image: "workshop.jpg", text: "Dos dias en las que tendremos un total de 9 presentaciones." }
 - {title: "Evento Social", image: "hackathon.jpg", text: "En esta ocasión contamos con el patrocinio de F5 para el evento social. El Día 6 tendrá lugar una cena en un restaurante que anunciaremos en breve." }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "53", specialCharacter: "+", info: "asistentes", detail: "de todas partes"}
 - {count: "24", specialCharacter: "+", info: "horas", detail: "de intercambio de información técnica, experiencias operacionales y conocimientos de ingeniería relacionados con los servicios de infraestructura de Internet."}
 - {count: "9", specialCharacter: "+", info: "ponentes", detail: "de clase mundial"}


# Latest News Block
latestNewsTitle: "Últimas noticias"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 9
rockstarSpeakersTitle: "Ponentes"
rockstarSpeakersButtonText: "Más información"

# Location Block
locationBlockTitle: "Ubicación"
eventLocationName: "CSUC/CATNIX"
eventLocationLink: "http://www.csuc.cat/es/el-csuc/el-consorcio/ubicacion"
eventStreetAddress: "C/ Gran Capità, s/n"
eventAddressLocality: "Barcelona"
eventAddressLocalityRegion: "Cataluña"
eventPostalCode: "08034"
eventAddressCountry: "España"
eventStartTime: "2017-04-06T09:30"
eventDoorTime: "09:00"
eventEndTime: "2017-04-06T18:00"
eventPlaceCoordinates: "41.387324, 2.111869"
mapCenterCoordinates: "41.387324, 2.111869"
mapMobileCenterCoordinates: "41.387324, 2.111869"

# Venue Block
venueBlockTitle: "Recinto"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
#venueSmallImage2: "venue_2.jpg"
#venueSmallImage3: "venue_3.jpg"
venueTitle: "CSUC/CATNIX"
venueFeatures: ["10.000 m2 construidos con forma cilíndrica", "Espacios de encuentro y meeting corners", "Entorno de investigación colaborativa e innovación."]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "¿Que está pasando?"
twitterHashTag: "esnog19"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Organizadores"
partnersTitle: "Patrocinadores"
partnersC4sponsorsButton: "Conviertase en patrocinador"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Footer
socialLinks:
 - {link: "https://plus.google.com/+EsnogNet", icon: "google-plus"}
 - {link: "https://twitter.com/intent/user?screen_name=ESNOG1", icon: "twitter"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Enlaces"
  links:
   - {link: "http://www.esnog.net/", text: "ESNOG.net"}
   - {link: "http://www.espanix.net/", text: "ESpanix"}
   - {link: "http://www.csuc.cat/es", text: "CSUC"}
   - {link: "http://www.catnix.net/es/", text: "CATNIX"}
   - {link: "https://f5.com/es", text: "F5"}
 -
  title: "Contacto"
  links:
   - {link: "mailto:gore-org@esnog.net", text: "gore-org@esnog.net"}
 -
  title: "FAQ"
  links:
   - {link: "https://esnog.slack.com", text: "Slack"}
   - {link: "https://plus.google.com/+EsnogNet/posts", text: "Video reuniones anteriores"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "Sobre nosotros"
aboutUs: "Un foro para el intercambio de información técnica, experiencias operacionales y conocimientos de ingeniería relacionados con los servicios de infraestructura de Internet.

Objetivos: Mejorar el intercambio de experiencias e información entre ingenierios,
mejorar la coordinacion entre redes en España y crear un foro abierto para mejorar la colaboración"

# Logistics Find Way Block
findWayTitle: "Como llegar"
findWayDistance: "Distancia"
findWayDriving: "CONDUCIENDO"
findWayWalking: "ANDANDO"
findWayBicycling: "BICICLETA"
findWayTransit: "TRANSPORTE PÚBLICO"
findWayFindFlight: "Encontrar vuelos"
logisticsMapCenterCoordinates: "41.387324, 2.111869"
logisticsMapMobileCenterCoordinates: "41.387324, 2.111869"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Conoce Barcelona"
directionDetailsCards:
 - {title: "Desde el aeropuerto", information: 'Con la nueva L9 – Sud. Desde el aeropuerto hasta Zona Universitária.'}
 - {title: "Transporte público", information: 'Aquí tienen enlaces a las páginas de <a href="http://www.tmb.cat/es/home">Bus, metro</a> y <a href="http://www.tram.cat/es/">Tram</a>.'}
 - {title: "Hoteles", information: 'El CSUC/CATNIX tiene una <a href="http://www.esnog.net/gore19/gore19-files/Hoteles_en_Barcelona.pdf">lista</a> de varios alojamientos <a href="https://www.google.com/maps/d/viewer?mid=zzqIqWVSmhQo.kOKSkhlMtsX0">cercanos</a>, utilizable para el evento.'}
directionDetailsWideCards:
 -
  title: "Hoteles"
  subCards:
   -
    title: ""
    links:
     - {link: "http://www.nh-hoteles.es/hotel/hesperia-sant-just", text: "NH Hesperia Sant Just"}
     - {link: "http://www.abbagardenhotel.com/es/home.html", text: "Abba Garden Hotel"}
     - {link: "http://www.atiramhotels.com/hoteles/barcelona/hotel-arenasatiram-cerca-camp-nou/", text: "Hotel Arenas Atiram"}
     - {link: "http://www.hotelmadanis.com/", text: "Hotel Madanis"}
     - {link: "https://www.mediumhoteles.com/es/espana/barcelona/sants/hotelmedium-prisma", text: "Hotel Medium Prisma"}

   -
    title: ""
    links:
     - {link: "http://www.hotelesplugues.com/", text: "Hotel Esplugues"}
     - {link: "http://www.barcelo.com/barcelohotels/es_es/hoteles/espana/barcelo", text: "Hotel Barceló Sants"}
     - {link: "http://www.hotelmadanisliceo.com/", text: "Hotel Madanis Liceo"}
     - {link: "http://www.hotelescatalonia.com/es/nuestros_hoteles/europa/espanya/catalunya/barcel", text: "Catalonia Rigoletto"}
   -
    title: ""
    links:
     - {link: "http://www.hotelbonanovapark.com/home/index.php", text: "Hotel Bonanova  Park"}
     - {link: "http://www.senatorbarcelonaspahotel.com/", text: "Senator Barcelona Spa"}
     - {link: "http://www.hotel-upperdiagonal.com/", text: "Hotel Upper Diagonal"}
     - {link: "http://www.marriott.com/hotels/travel/bcnsu-ac-hotel-victoriasuites/", text: "AC Hotel Victoria Suites"}
 -
  title: "Residencias"
  subCards:
   -
    title: ""
    links:
     - {link: "http://www.resa.es/es/residencias/barcelona/residencia-universitaria-torre-girona/residencia/", text: "RESA Torre Girona (a 9 minutos del CSUC)"}
     - {link: "http://www.resainn.com/alojamiento/barcelona/residencia-investigadors/", text: "RESA d’Investigadors (media hora en metro L3)"}


# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
